#!/usr/bin/env python3
"""
Demo script showing RTSP authentication usage
"""

print("="*60)
print("Hailo-10h RTSP VLM Analyzer - Authentication Demo")
print("="*60)

print("\n1. ANALYZER (Raspberry Pi with Hailo-10H):")
print("-"*40)
print("Basic usage:")
print("  python rtsp_vlm_analyzer.py --rtsp rtsp://192.168.1.100:554/stream")
print()
print("With authentication:")
print("  python rtsp_vlm_analyzer.py \\")
print("    --rtsp rtsp://192.168.1.100:554/stream \\")
print("    --rtsp-user admin \\")
print("    --rtsp-pass password123")
print()
print("With authentication and custom settings:")
print("  python rtsp_vlm_analyzer.py \\")
print("    --rtsp rtsp://192.168.1.100:554/stream \\")
print("    --rtsp-user admin \\")
print("    --rtsp-pass password123 \\")
print("    --default-question \"How many people are visible?\" \\")
print("    --interval 30 \\")
print("    --save-frames \\")
print("    --results-dir ./security_logs")
print()
print("Test without Hailo hardware:")
print("  python rtsp_vlm_analyzer.py \\")
print("    --rtsp rtsp://192.168.1.100:554/stream \\")
print("    --simulate \\")
print("    --verbose")

print("\n2. FRAME SENDER (Other devices):")
print("-"*40)
print("Basic usage:")
print("  python frame_sender.py \\")
print("    --analyzer http://192.168.1.50:8080 \\")
print("    --rtsp rtsp://192.168.1.101:554/stream")
print()
print("With authentication:")
print("  python frame_sender.py \\")
print("    --analyzer http://192.168.1.50:8080 \\")
print("    --rtsp rtsp://192.168.1.101:554/stream \\")
print("    --rtsp-user admin \\")
print("    --rtsp-pass camera123")
print()
print("With authentication and custom question:")
print("  python frame_sender.py \\")
print("    --analyzer http://192.168.1.50:8080 \\")
print("    --rtsp rtsp://192.168.1.101:554/stream \\")
print("    --rtsp-user admin \\")
print("    --rtsp-pass camera123 \\")
print("    --question \"What objects are in the frame?\" \\")
print("    --interval 60")
print()
print("Without motion detection (time-based only):")
print("  python frame_sender.py \\")
print("    --analyzer http://192.168.1.50:8080 \\")
print("    --rtsp rtsp://192.168.1.101:554/stream \\")
print("    --rtsp-user admin \\")
print("    --rtsp-pass camera123 \\")
print("    --no-motion \\")
print("    --interval 300  # Every 5 minutes")

print("\n3. RTSP URL FORMATS:")
print("-"*40)
print("Embedded credentials in URL:")
print("  rtsp://username:password@camera_ip:554/stream")
print()
print("Separate arguments (recommended):")
print("  --rtsp rtsp://camera_ip:554/stream \\")
print("  --rtsp-user username \\")
print("  --rtsp-pass password")
print()
print("With query parameters:")
print("  rtsp://username:password@camera_ip:554/stream?channel=1&subtype=0")

print("\n4. SECURITY BEST PRACTICES:")
print("-"*40)
print("✓ Use environment variables for passwords:")
print("  export RTSP_PASSWORD=\"your_password\"")
print("  python rtsp_vlm_analyzer.py --rtsp rtsp://camera:554/stream \\")
print("    --rtsp-pass $RTSP_PASSWORD")
print()
print("✓ Use .netrc file:")
print("  echo \"machine camera_ip login admin password secret\" >> ~/.netrc")
print("  chmod 600 ~/.netrc")
print()
print("✓ Set script permissions:")
print("  chmod 700 rtsp_vlm_analyzer.py")
print("  chmod 600 config.yaml  # if using config file")
print()
print("✓ Use separate service account for cameras")
print("✓ Change default camera passwords")
print("✓ Use VLAN segmentation for camera network")

print("\n5. TROUBLESHOOTING:")
print("-"*40)
print("Test RTSP connection with VLC:")
print("  vlc rtsp://username:password@camera_ip:554/stream")
print()
print("Test with ffmpeg:")
print("  ffmpeg -i rtsp://username:password@camera_ip:554/stream -f null -")
print()
print("Check OpenCV backends:")
print("  python -c \"import cv2; print(cv2.getBuildInformation())\" | grep -i ffmpeg")
print()
print("Enable verbose logging:")
print("  python rtsp_vlm_analyzer.py --rtsp rtsp://camera:554/stream --verbose")

print("\n" + "="*60)
print("Quick Start Commands:")
print("="*60)
print("# On Raspberry Pi:")
print("git clone https://github.com/opivankristovi/Hailo-10h_RTSP_VLM")
print("cd Hailo-10h_RTSP_VLM")
print("./setup.sh")
print("source venv/bin/activate")
print()
print("# Test with simulation:")
print("python rtsp_vlm_analyzer.py --rtsp rtsp://test:554/stream --simulate")
print()
print("# Real usage with auth:")
print("python rtsp_vlm_analyzer.py \\")
print("  --rtsp rtsp://YOUR_CAMERA_IP:554/stream \\")
print("  --rtsp-user YOUR_USERNAME \\")
print("  --rtsp-pass YOUR_PASSWORD")
print("="*60)